version: '3.8'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ragdb
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4:8
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  app:
    build: .
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/ragdb
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      API_KEY: change-me
      CORS_ALLOWED_ORIGINS: http://localhost:3000
      RATE_LIMIT_WINDOW_SECONDS: 60
      RATE_LIMIT_MAX_REQUESTS: 120
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db-data:


